# Vitcoin Core Configuration
server=1
listen=1
rpcuser=vitadmin
rpcpassword=vitsecurepass123
rpcport=22555
port=22556

# Allow all IPs to connect via RPC (Railway Gateway ke liye zaroori hai)
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

[main]
rpcbind=0.0.0.0

